#!/bin/bash

#
# run background processes
#
rm -fr $HOME/.local/share/Trash/files/* $HOME/.local/share/Trash/info/* &

# allow root to connect to X server (for sudo and stuff)
xhost +si:localuser:root

# prepare environment to use gpg-agent
eval $(gpg-agent --daemon)

#
# run X applications
#
(
  # wait for fluxbox to start
  while ! pidof fluxbox
  do
    sleep 0.5
  done
  sleep 0.5

  ( set -e ; fbsetroot -solid black ; FBP="`pidof fluxbox`" ; while [ "`pidof fluxbox`" = "$FBP" ] ; do rand_wallpaper ; sleep 1500 ; done ) &
  #xfce4-power-manager &
  #krandrtray &
  #keepassx &
  wicd-client -t &
  transmission-gtk -m &
  akregator --hide-mainwindow  &
  prevent_monitor_sleep &
) &

#
# RUN FLUXBOX
#
exec ssh-agent fluxbox -log "/tmp/.fluxbox-${USER}-$(date +%s)-XXXXXXXXX.log"
