#!/bin/bash
set -euo pipefail

app=$(basename "$0")

if [ $# -lt 2 ]
then
  echo "$app <role> <host> [other/ansible/params]" >&2
  exit 2
fi
role=$1
target=$2
shift 2

exec ansible -m include_role -a name="$role" "$target" "$@"
