#!/bin/bash
APP=$(basename "$0")

function log
{
  MSG="$(date): $APP: $*"
  echo   "$MSG"
  logger "$MSG"
}

swayidle -w \
  timeout 10 \
    'swaymsg "output * dpms off"' \
    resume 'swaymsg "output * dpms on"' &
MONITOR=$!

log "locking screen"
swaylock --color 00000000 --show-failed-attempts # --daemonize
log "screen unlocked"

kill "$MONITOR"
wait "$MONITOR"
log "monitor script stopped"

log "disabling screen blanking"
swaymsg output "*" dpms on
