#!/bin/bash
set -eu -o pipefail

if [ $# -ne 2 ]
then
  echo "$0 <dev_name> <interval_sec>" >&2
  exit 1
fi
DEV=$1
DT=$2
shift 2

iostat -dym -p "$DEV" "$DT" \
  | grep --line-buffered "^$DEV" \
  | awk '{ print "T", $2, "R", $3 "M", "W", $4 "M" }'
