#!/bin/bash
set -eu -o pipefail

if [ $# -lt 2 ]
then
  echo "$(basename "$0") <dpi> <output.jpg> [options]" >&2
  exit 2
fi

DPI=$1
FILE=$2
shift 2

exec scanimage \
       --device-name 'pixma:04A91913_470924' \
       --progress \
       --resolution "${DPI}dpi" \
       --mode Color \
       --format 'jpeg' \
       --output-file "$FILE" \
       "$@"
