#!/bin/bash
set -euo pipefail

tmp=$(mktemp "/tmp/.run-in-openbox-cmd.XXXXXX")
trap "rm -f '$tmp'" EXIT
chmod u+x "$tmp"

cat >> "$tmp" <<EOF
#!/bin/bash
set -euo pipefail
trap 'openbox --exit' EXIT
cd $(printf '%q ' "$PWD")
$(printf '%q ' "$@")
EOF

openbox --startup "$tmp"
