#!/bin/bash

if [ $# -lt 1 ]
then
  echo "$0 <app> [<argv>]" >&2
  exit 2
fi

HOSTS+=("duckduckgo.com")
HOSTS+=("hackaday.com")
HOSTS+=("google.com")

DELAY=1

while true
do
  for host in "${HOSTS[@]}"
  do
    if curl -s "https://$host/" > /dev/null 2>&1
    then
      exec "$@"
      exit "$?"
    fi
  done
  echo "$0: no internet - waiting for $DELAY [s]"
  sleep "$DELAY"
  DELAY=$((DELAY >= 100 ? 50 : DELAY+1))
done
