#!/bin/bash
set -eu -o pipefail
readonly out_dir="$1"
shift 1
exec yt-dlp-docker \
    "$out_dir" \
    --continue \
    --no-overwrites \
    --ignore-errors \
    --extract-audio \
    --audio-format vorbis \
    "$@"
